### ISSUE TITLE
JS: Struct field getters for opaque types should handle their caching

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#170]
Currently when we return a struct containing opaques we generate a struct with a getter:

https://github.com/rust-diplomat/diplomat/blob/517f1a4423fb8a88d5af9dcd1465efe8fb9987ec/example/js/api.mjs#L166-L171

and then the method being generated immediately calls that getter and replaces it with the value:

https://github.com/rust-diplomat/diplomat/blob/517f1a4423fb8a88d5af9dcd1465efe8fb9987ec/example/js/api.mjs#L99-L105

We should probably not have this burden be on the method and instead handle this automagically in struct getter code.

**Comment by Manishearth** [comment]
> I'm a little confused by what's going on in the second snippet

The `out.fdf` calls the getter once, and the `defineProperty()` _overrides_ the getter to replace it with the value.

> but I was wondering if this would involve translating non-opaque struct fields eagerly to JS objects at the boundary instead of lazily reading from an underlying wasm buffer?

So, we _could_ transform non-opaque structs _completely eagerly_ at the boundary, that would probably work fine. But my suggestion here is narrower, we should have the getter handle caching internally, and we should remove the weird "call the getter and replace the property" thing.

Options are going to make it trickier since we can't use `null` as a sentinel value anymore.

**Comment by QnnOkabayashi** [comment]
I think it would be nice to transform the object completely, because then we wouldn't need to hold an underlying buffer, allowing us to more easily reason about when we can free wasm memory. The only downside I see to this is that if not all the struct's fields are needed, it would incur unnecessary overhead. But I think that's a fair trade off since if you should probably just design a more minimal return type if you care about that.

**Comment by Manishearth** [comment]
Sounds good!

**Comment by QnnOkabayashi** [comment]
Fixed by https://github.com/rust-diplomat/diplomat/pull/176
