### ISSUE TITLE
Figuring out 'static

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#261]
We currently support `'static`, but it might not actually be fully safe since most languages have no such thing.

We should probably be generating lifetime annotations and borrows. C++ can simply emit a doc comment as usual. For JS, we can:

  - support a `#[diplomat::static_consumed_by_return]` attribute that marks the static as being consumed by the return value. We can potentially support some field syntax if only a subpart of the return value does this.
  - By default stash the input into some global thingy. If that attribute is present, treat it as a borrow instead.

This is because `'static` is often really just borrowed for the purposes of a particular return, but not always.

We could also ask people to use lifetimes (potentially phantom lifetimes) to achieve the same effect, but it might require e.g. having an `ICU4XBlobDataProvider` and `ICU4XBlobDataProviderBorrowed<'a>`

**Comment by robertbastian** [comment]
Lifetimes don't work for the purpose of `ICU4XBlobDataProvider`, as a `DataPayload` might outlive the provider, so the blob has to be either owned (and wrapped in Rc on the Dart side), or `'static`.

I think a good first step would be to ignore functions accepting `&'static` arguments in WASM generation, as there doesn't seem to be any `static`/`const` in WASM.

**Comment by robertbastian** [comment]
But the edge will be between the `ICU4XBlobDataProvider` and its backing data. When the provider gets dropped, the blob will also be cleaned up. We don't at the moment have a way to add an edge between the provider and its `DataResponse`s, as inside Rust that's managed by reference counting or static refs.

**Comment by robertbastian** [comment]
In #264 I'm just leaking it, that should work?

**Comment by Manishearth** [comment]
yep

**Comment by QnnOkabayashi** [comment]
Is there some reason we can't just disallow inputs to be static refs? That way we could still produce static refs from the Rust side within opaques but not have to worry about leaking memory.

**Comment by robertbastian** [comment]
Static ref inputs is something we want for C, as we can make some Rust code more efficient by operating on static refs, and in C we can just tell the user they're responsible for keeping it alive.

**Comment by QnnOkabayashi** [comment]
Is there a reason it can't just be a regular lifetime? In C/C++, it will just be the case that anything that borrows from it will just say "oh make sure that thing lives longer", and if you leak it (or have it in .data), then you don't even have to worry about it.

My concern is that this adds a lot of special-case handling to Diplomat (i.e. `#[diplomat::static_consumed_by_return]`, which we can't even statically verify afaik), and there's no good reason to leak in JS when we can just add as many edges as needed to keep it alive.

**Comment by robertbastian** [comment]
We have a use case in ICU4X that requires borrowing inputs for a static lifetime so that the returned object can return objects without lifetimes. See https://github.com/rust-diplomat/diplomat/issues/261#issuecomment-1259732893. This means that we have to distinguish the lifetimes "make sure that foo lives at least as long as the output" and "make sure that foo lives forever".

**Comment by QnnOkabayashi** [comment]
I understand why we might want to borrow statically within pure Rust code, but I'm having trouble coming up with cases where C is providing some useful `'static` data that Rust needs. In ICU4X's case, are we thinking that this `'static` data from C comes from .data? Or from leaking heap allocs?

**Comment by robertbastian** [comment]
Basically we want to get rid of this allocation: https://github.com/unicode-org/icu4x/blob/main/ffi/diplomat/src/provider.rs#L139

If we can change that method to accept a `'static` lifetime, we can use `BlobDataProvider`'s `&'static [u8]` constructor instead of the `Box<[u8]>` one. On the C side this can be either leaked memory or .data.

**Comment by QnnOkabayashi** [comment]
But where would the C side be getting the data from in the first place? If we're getting it dynamically, it makes more sense to have a Rust fn that handles the creation and leaking of the data, because then we can hide it behind an opaque that just wraps a `&'static [u8]`. If we're getting it from the C program's .data, then I can see why we'd want to do this, but I have a hard time understanding where we'd ever do that.

The reason I'm so adamant about this is because I realized that just banning static inputs simplifies everything so much, and since it really doesn't make sense to leak in GC languages when we can just add edges whenever we want, and since the `static_in_return` attr isn't statically verifiable by Diplomat.

**Comment by Manishearth** [comment]
> a Rust fn that handles the creation and leaking of the data,

Not if the loading is managed by C; the problem is that we want to give the application some freedom here.

In ICU4X we want data loading to be super flexible; and from an FFI point of view ideally people don't have to build any Rust, so loading static data would ideally be done by loading it into C and having it over to Rust.

**Comment by robertbastian** [comment]
For an example of what this would look like in C: https://github.com/unicode-org/icu4x/blob/main/ffi/diplomat/c/examples/fixeddecimal_tiny/test.c#L12

**Comment by robertbastian** [comment]
This will also save us an allocation in WASM. Currently we need to copy the array into the diplomatBuf, and then Rust has to copy it again because the lifetime is too short.

Leaking is bad though, repeatedly creating data providers should not leak repeatedly. So I really don't know how to do this in WASM, as the platform doesn't seem to support any `static`/`const` objects.

**Comment by Manishearth** [comment]
A thing that would be cool for the WASM (but not C++) situation would be a `DiplomatOwned<Rc<[u8]>>` (etc) type, which on the JS API side behaves identically to an `&[u8]` method, but the internal bindings will instead allocate an Rc for you, and pass it in owned

**Comment by robertbastian** [comment]
We don't even need to deal with `Rc`, we just need a way to pass `Box<[u8]>`. 

We should hide the `&'static [u8]` constructor in WASM, it doesn't make sense to have it because there is no `static` in JS. However, the current `&[u8]` constructor does two allocations in Rust memory, which we could reduce by interpreting the pointer we get from WASM as `Box<[u8]>` (and not freeing it in WASM after the function call). We're allowed to do this and free it in Rust because we allocated in Rust memory (`wasm.diplomat_alloc`).

In C I'm not sure whether something like this is allowed, because Rust isn't allowed to free non-Rust-allocated memory. But it's not really required, because C can just do manual memory management with the `&'static` constructor (although it would be nice to have the owned constructor, so that non-static blobs don't have to be leaked).

**Comment by Manishearth** [comment]
Yeah, I'm just trying to design things in a future proof way, hence the Rc.

I agree that we should hide that constructor, I think the `DiplomatOwned` version is what we should do instead (for JS only, it doesn't make as much sense in C++, but we could potentially expose it for std::vector _if_ we get them to sign a waiver that they know it's technically ub :stuck_out_tongue: )

For now though, I think making `&'static` work by leaking is an acceptable easy path forward.

**Comment by Manishearth** [comment]
hmm, in general my attitude is that with per-backend disabling and renaming we can get more flexibility, and for situations like this we shouldn't try for one-size-fits-all solutions

**Comment by QnnOkabayashi** [comment]
> For now though, I think making `&'static` work by leaking is an acceptable easy path forward.

I'm okay with this outcome, ideally as long as we mark that it's subject to change. I don't want to be stuck with a temp solution for backwards compatibility reasons. But if it's just for ICU4X use then I think it's fine.

**Comment by sffc** [comment]
Coming in a bit late to this conversation.

It makes complete sense for `'static` to exist in C/C++, because it is actually a real thing you can have, as shown in @robertbastian's `decimal_bn_en.h` example.

For WASM, why not treat lifetimeless types like `T` as `T<'static>`, and any methods that take a `'static` argument get a proper GC edge, just like they do with `T<'a>` methods that take a `'a` argument.

Languages like Python and PHP are interesting, because they are GC'd and yet they do have support for proper static memory. But I guess it's harmless to still add a GC edge in those cases.

**Comment by robertbastian** [comment]
#373 introduced `supports = memory_sharing`, which is the same as a potential `supports = statics`. We can gate methods that accept `&'static` on that.
