### ISSUE TITLE
IDL as a backend?

### ISSUE THREAD

**Issue by soc** [rust-diplomat/diplomat#322]
What are your thoughts on using an interface description language as a target backend, such that tools can implement the IDL-to-host-language once, instead of creating an N:M matrix where every source languages N need to write bindings for M host languages?

In the Windows ecosystem, WinMD seems to be quite successful with this approach.

**Comment by Manishearth** [comment]
This requires cross-industry agreement on an idiomatic language-to-IDL mapping, and it starts becoming _bidirectional_.

Diplomat is trying to be a solution for calling Rust code specifically, since we can make choices that make sense for Rust code. Within the context of Diplomat it is still 1-to-M.

**Comment by Manishearth** [comment]
If there exists an IDL format I'm not opposed to generating it via Diplomat, though. I just don't think that the scope should be expanded to fixing the problem for multiple source languages

**Comment by soc** [comment]
Sorry for asking.

**Comment by Manishearth** [comment]
No need to apologize!
