### ISSUE TITLE
JS2 Backend: Opaque Lifetime Edges

### ISSUE THREAD

**Issue by ambiguousname** [rust-diplomat/diplomat#525]
For opaques: If we don't want to retain the `selfEdge` argument itself, we could `this.#selfEdge.push(...selfEdge)` (see `example/ICU4XDataProvider` for an example of this)

Need to do more testing for anything borrowed: slices, structs, opaques, etc.

**Comment by sffc** [comment]
Specific case: https://github.com/rust-diplomat/diplomat/pull/487#discussion_r1651463232

**Comment by ambiguousname** [comment]
Overly conservative edge setup.

For instance, Foo.bar should have `this.#aEdge` instead of `this` for `aEdges`.

**Comment by ambiguousname** [comment]
We could either immediately destroy anything, or register a garbage collection hook

**Comment by ambiguousname** [comment]
Set ptr to null when opaque is destroyed

**Comment by ambiguousname** [comment]
Possible values: symbol or bigints

**Comment by ambiguousname** [comment]
When returning a reference to an opaque, skip the step where you register the opaque with the FinalizationRegistry

**Comment by Manishearth** [comment]
(and make sure selfEdge is appropriately populated when a method does this)

**Comment by ambiguousname** [comment]
Notes from today:
- Proper use of FinalizationRegistry
  - We discussed unconditional registry, but what if a constructor returns a reference to an opaque?
  - @robertbastian  For dart, if there are lifetime edges, we borrow instead. 
- Proper way to store edges
  - The difference between `this.#aEdge = bEdge;` and `this.#aEdge = [bEdge, cEdge];` when constructing opaques. Which is preferred?
      - @robertbastian For the second case, you have a list of lists, when you pass this to someone, you can add it to the sublists. Not entirely clear on this either; at some point in Rust it iterates through the list of lists and adds itself to every list. 
      - Need the second option for nested borrowed fields and multiple lifetimes
 
Not a priority, not at least until Manish gets back

**Comment by Manishearth** [comment]
> We discussed unconditional registry, but what if a constructor returns a reference to an opaque?


That's what selfEdge is for, in this situation you don't want to create a finalization registry but instead add the appropriate self edge. In Dart we do this:

https://github.com/rust-diplomat/diplomat/blob/88b91e567b5912c5b4a243b6b85e8613d8c9f4cb/feature_tests/dart/lib/src/OpaqueMutexedString.g.dart#L16-L20





> The difference between `this.#aEdge = bEdge;` and `this.#aEdge = [bEdge, cEdge];` when constructing opaques. Which is preferred?

Flatter is better so we don't create a billion arrays, _however_ using one level of array nesting ends up being nice because you can pass lists to other consumers. The former approach doesn't let you do this so you may need to fully compute edges for all nested fields.

This is essentially the distinction between the `borrowing_params` and `borrowing_fields` approach: `borrowing_params` is what Dart uses and what I would recommend.

The docs on `borrowing_params` are quite extensive about how that method works.

**Comment by ambiguousname** [comment]
Noticing actually that edges are set up for opaques before construction.

So the current setup is something like:
```js
constructor (selfEdge, aEdge) {
this.#selfEdge = selfEdge;
this.#aEdge = aEdge;
}

let selfEdge = [this];
let aEdge = [selfEdge];
new (selfEdge, aEdge);
```
(Not meant to be a realistic representation of borrowing, just how arrays get copied)

Should be okay? Unless I'm missing something.

**Comment by Manishearth** [comment]
@ambiguousname unsure exactly what you're asking, but, yes, the edge arrays should be passed down in the constructor, and the constructor may choose to combine edge arrays if it needs (this only happens in structs)

**Comment by ambiguousname** [comment]
Ah, I didn't realize that combination happens in structs. I'll take a look and adjust on Monday, then. Thank you!
