### ISSUE TITLE
Should `namespace` be `library_name` or something?

### ISSUE THREAD

**Issue by robertbastian** [rust-diplomat/diplomat#589]
We don't support nested namespaces afaik, and so far we're using it as what basically is the library name (e.g. `icu4x`). If we called it library name, it could also be useful for Dart, maybe JS, Kotlin, and C (as a prefix).

**Comment by Manishearth** [comment]
> We don't support nested namespaces afaik

We absolutely do, it's just not polished: in C++ you can do `namespace = "foo::bar"` and it works. I'd like other backends to support that in the long run, it's useful to be able to further organize your code. It's not been priority for me to do this because ICU4X doesn't need it.

Most likely it would be the syntax of `namespace = "foo::bar"` or `namespace = "foo.bar"` and the code automatically detects the syntax and transforms it to the appropriate convention.

Now that I think about it more I think https://github.com/rust-diplomat/diplomat/pull/572 might have broken this. But I do intend to have this functionality in here, aspirationally. Filing a separate issue.

**Comment by Manishearth** [comment]
Filed https://github.com/rust-diplomat/diplomat/issues/591 for nested namespaces. I do think `library_name` and `namespace` are somewhat _separate_ features that likely interact strongly: for ICU4X's purpose so far `namespace` is serving its purpose but I think being able to set the library name from the config would be really really nice, and we can then have namespacing _on top of that_ for code organization (e.g. to do `icu4x::properties::CodePointSet` if we ever decide to)

**Comment by Manishearth** [comment]
Closing in favor of https://github.com/rust-diplomat/diplomat/issues/688
